import { Lang, pathFor } from './practice';
export const treatments=[
 {id:'cleaning',slug:{de:'zahnreinigung',en:'professional-cleaning'},icon:'sparkles',source:'https://www.kzbv.de/patienten/medizinische-infos/vorsorge/professionelle-zahnreinigung/',
 de:{title:'Prophylaxe & Zahnreinigung',short:'Damit aus gesunden Zähnen ein langfristig gutes Gefühl wird.',headline:'Vorsorge, die zu Ihnen passt.',intro:'Professionelle Zahnreinigung kann die tägliche Mundpflege ergänzen. Der Bedarf wird individuell beurteilt.',suitability:'Sinnvoll je nach Mundgesundheit und persönlichem Risiko.',process:'Nach der Untersuchung werden Beläge entfernt, Zahnoberflächen poliert und Pflegehinweise besprochen.',risks:'Vorübergehende Empfindlichkeit oder gereiztes Zahnfleisch sind möglich. Informieren Sie das Team über Erkrankungen und Medikamente.',duration:'Der Zeitbedarf richtet sich nach dem Befund.',cost:'Die PZR ist normalerweise eine private Leistung. Manche Kassen leisten Zuschüsse; fragen Sie vorab nach.',after:'Folgen Sie den persönlichen Pflegeempfehlungen. Auch die Nachsorgeintervalle werden individuell festgelegt.'},
 en:{title:'Prevention & cleaning',short:'Helping healthy teeth stay a lasting part of your wellbeing.',headline:'Prevention that fits you.',intro:'Professional cleaning can complement daily oral care. Individual needs are assessed first.',suitability:'Suitability depends on oral health and personal risk.',process:'After examination, deposits are removed, surfaces polished and home care discussed.',risks:'Temporary sensitivity or gum irritation may occur. Tell the team about conditions and medicines.',duration:'Time needed depends on the findings.',cost:'Cleaning is usually privately charged. Some insurers contribute; check beforehand.',after:'Follow your individual care advice. Follow-up intervals are tailored to you.'}},
 {id:'restoration',slug:{de:'zahnerhaltung',en:'tooth-preservation'},icon:'tooth',source:'https://www.kzbv.de/patienten/medizinische-infos/karies-und-fuellungen/wie-entsteht-karies/',
 de:{title:'Zahnerhaltung',short:'Natürliche Zähne erhalten. Mit einer Behandlung, die zu Ihrem Befund passt.',headline:'Ihre eigenen Zähne im Mittelpunkt.',intro:'Füllungen können geschädigte Zahnsubstanz ersetzen. Welche Versorgung geeignet ist, hängt von Größe und Lage des Defekts ab.',suitability:'Für behandelbare Zahndefekte nach zahnärztlicher Untersuchung.',process:'Befund und Materialien werden besprochen, geschädigte Bereiche behandelt und die Füllung angepasst.',risks:'Empfindlichkeit, Materialunverträglichkeit oder weitere Behandlungsbedürftigkeit sind möglich.',duration:'Ein oder mehrere Termine, je nach Aufwand.',cost:'Kassenleistung und mögliche Mehrkosten hängen von Versorgung und Material ab. Ein Vergleich der Optionen gehört zur Planung.',after:'Pflegen Sie Zähne und Zwischenräume sorgfältig; bei anhaltenden Beschwerden melden Sie sich in der Praxis.'},
 en:{title:'Tooth preservation',short:'Keeping natural teeth, with care tailored to your individual findings.',headline:'Your natural teeth come first.',intro:'Fillings can replace damaged tooth structure. The size and position of the defect guide the choice.',suitability:'Treatable defects following a dental examination.',process:'Findings and materials are discussed, damaged areas treated and the restoration adjusted.',risks:'Sensitivity, material reactions or further treatment needs are possible.',duration:'One or more appointments depending on complexity.',cost:'Insurance cover and additional charges depend on the restoration and material. Discuss your options first.',after:'Clean teeth and interdental spaces carefully. Contact the practice for persistent discomfort.'}},
 {id:'gums',slug:{de:'parodontologie',en:'gum-care'},icon:'leaf',source:'https://www.kzbv.de/patienten/medizinische-infos/parodontitis/behandlung-der-parodontitis/',
 de:{title:'Parodontologie',short:'Gesundes Zahnfleisch. Eine wichtige Grundlage für feste Zähne.',headline:'Gesundes Zahnfleisch verdient Aufmerksamkeit.',intro:'Parodontitis betrifft den Zahnhalteapparat. Die Behandlung richtet sich nach Ausprägung und individuellen Risikofaktoren.',suitability:'Bei diagnostizierter Erkrankung des Zahnhalteapparats.',process:'Befunderhebung, Aufklärung und Reinigung werden mit einer strukturierten Nachsorge kombiniert.',risks:'Empfindliche Zahnhälse und Veränderungen des Zahnfleischverlaufs können auftreten. Weitere Maßnahmen können notwendig werden.',duration:'Mehrere Schritte über einen individuell geplanten Zeitraum.',cost:'Die mögliche Kostenübernahme wird vorab anhand der Voraussetzungen Ihrer Versicherung geklärt.',after:'Regelmäßige Nachsorge und sorgfältige häusliche Mundpflege sind wesentlich.'},
 en:{title:'Gum care',short:'Healthy gums are an important foundation for stable teeth.',headline:'Give your gums the care they need.',intro:'Periodontitis affects the tissues supporting teeth. Treatment depends on its extent and individual risk.',suitability:'For diagnosed disease of the tooth-supporting tissues.',process:'Assessment, information and cleaning are followed by a structured maintenance plan.',risks:'Sensitive roots and changes to the gum line may occur. Further treatment may be needed.',duration:'Several stages over an individual timeline.',cost:'Potential insurance cover is checked against eligibility before treatment.',after:'Ongoing reviews and careful daily oral hygiene are important.'}},
 {id:'replacement',slug:{de:'zahnersatz',en:'restorative-dentistry'},icon:'gem',source:'https://www.kzbv.de/patienten/medizinische-infos/zahnersatz/',
 de:{title:'Zahnersatz',short:'Wieder unbeschwert sprechen, essen und lächeln – individuell geplant.',headline:'Eine Lösung, die zu Ihnen passt.',intro:'Kronen, Brücken oder herausnehmbarer Zahnersatz können Funktion und Aussehen ergänzen. Die Auswahl braucht eine persönliche Untersuchung.',suitability:'Bei geschädigten oder fehlenden Zähnen, abhängig vom Gesamtbefund.',process:'Beratung, Planung, Vorbereitung, Anfertigung und Anpassung erfolgen in abgestimmten Schritten.',risks:'Druckstellen, Empfindlichkeit und Reparaturbedarf sind möglich. Voraussetzungen und Alternativen werden besprochen.',duration:'Meist mehrere Termine; ein Zeitplan entsteht nach der Untersuchung.',cost:'Ein Heil- und Kostenplan erläutert Versorgung und voraussichtlichen Eigenanteil.',after:'Pflege und Kontrollen werden auf den gewählten Zahnersatz abgestimmt.'},
 en:{title:'Restorative dentistry',short:'Comfort in speaking, eating and smiling, with individual planning.',headline:'A solution that suits you.',intro:'Crowns, bridges or removable dentures can restore function and appearance. Selection needs an individual examination.',suitability:'Damaged or missing teeth, depending on the overall findings.',process:'Consultation, planning, preparation, fabrication and fitting are coordinated in stages.',risks:'Pressure points, sensitivity and repairs may occur. Discuss prerequisites and alternatives.',duration:'Usually several visits; a timeline follows examination.',cost:'A treatment and cost plan explains the option and expected personal contribution.',after:'Care and reviews are tailored to your restoration.'}},
 {id:'children',slug:{de:'kinderzahnmedizin',en:'childrens-dentistry'},icon:'smile',source:'https://www.bzaek.de/fileadmin/PDFs/presse/mdm05/Mundgesundheit_von_Anfang_an.pdf',
 de:{title:'Kinderzahnmedizin',short:'Kleine Zähne, große Bedeutung. Mit Ruhe und kindgerechten Erklärungen.',headline:'Ein guter Anfang für kleine Zähne.',intro:'Frühe Vorsorge begleitet die Entwicklung der Zähne und unterstützt Eltern bei der Mundpflege.',suitability:'Für Kinder; die passende Untersuchung richtet sich nach Alter und Entwicklung.',process:'Kennenlernen, altersgerechte Untersuchung und Beratung zur häuslichen Zahnpflege.',risks:'Untersuchungen können ungewohnt sein. Weitergehende Behandlungen werden gesondert erklärt und abgestimmt.',duration:'Der Termin wird nach Alter und Bedarf geplant.',cost:'Vorsorgeleistungen und mögliche Zusatzleistungen werden vorab eingeordnet.',after:'Eine altersgerechte Putzroutine hilft. Individuelle Fluoridempfehlungen und Kontrollintervalle werden besprochen.'},
 en:{title:'Children’s dentistry',short:'Little teeth matter. With patience and age-appropriate explanations.',headline:'A good start for little teeth.',intro:'Early prevention supports dental development and helps parents with daily oral care.',suitability:'For children, with examinations matched to age and development.',process:'Getting acquainted, an age-appropriate examination and home-care guidance.',risks:'Examinations can feel unfamiliar. Any further treatment is explained and agreed separately.',duration:'Appointments are planned around age and need.',cost:'Preventive benefits and optional extras are explained beforehand.',after:'Build an age-appropriate brushing routine. Discuss individual fluoride advice and review intervals.'}},
 {id:'checkup',slug:{de:'vorsorge',en:'check-ups'},icon:'shield',source:'https://www.kzvb.de/patient/vorsorge',
 de:{title:'Kontrolle & Beratung',short:'Fragen klären, Veränderungen erkennen und nächste Schritte verstehen.',headline:'Klarheit für Ihre Mundgesundheit.',intro:'Eine Kontrolluntersuchung schafft einen Überblick über Zähne und Zahnfleisch.',suitability:'Regelmäßig und bei Veränderungen; den passenden Abstand empfiehlt das Behandlungsteam.',process:'Beschwerden werden besprochen, die Mundsituation untersucht und mögliche nächste Schritte erklärt.',risks:'Ein Befund kann weitere Diagnostik erfordern. Röntgenaufnahmen erfolgen nur bei entsprechender Indikation.',duration:'Abhängig von Untersuchungsumfang und Gesprächsbedarf.',cost:'Die Abrechnung richtet sich nach Leistung und Versicherungsstatus. Zusätzliche Leistungen werden vorab besprochen.',after:'Empfohlene Kontrollen einhalten und neue oder anhaltende Beschwerden abklären lassen.'},
 en:{title:'Check-ups & advice',short:'Clear answers, early observations and understandable next steps.',headline:'Clarity about your oral health.',intro:'A check-up provides an overview of your teeth and gums.',suitability:'Regularly and when changes occur; your team advises on intervals.',process:'Concerns are discussed, oral health examined and potential next steps explained.',risks:'Findings may require further tests. X-rays are taken only when indicated.',duration:'Depends on the examination and discussion needed.',cost:'Charges depend on services and insurance status. Additional services are discussed first.',after:'Attend recommended reviews and have new or persistent problems assessed.'}}
];
export function treatmentPath(lang:Lang,t:typeof treatments[number]){return `${pathFor(lang,'services')}/${t.slug[lang]}`;}
