'use client';
import {useState} from 'react';
import {ArrowRight,ArrowLeft,CalendarDays,Phone,Menu,X,Expand,Printer} from 'lucide-react';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {Sheet,SheetTrigger,SheetContent,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {practice,ui,faq,Lang,PageKey,pathFor} from '@/lib/practice';

export function BookingButton({lang,className='',short=false}:{lang:Lang;className?:string;short?:boolean}){
 const t=ui[lang];
 return <Dialog><DialogTrigger asChild><button className={`btn ${className}`} aria-label={short?t.bookShort:t.appointment}><CalendarDays aria-hidden="true"/><span className="booking-label">{short?t.bookShort:t.appointment}</span><span className="booking-short" aria-hidden="true">{t.bookShort}</span></button></DialogTrigger><DialogContent className="booking-dialog" showCloseButton={false}><DialogClose className="dialog-close" aria-label={t.close}><X/></DialogClose><div className="booking-icon"><CalendarDays/></div><DialogTitle>{t.bookingTitle}</DialogTitle><DialogDescription>{t.bookingDescription}</DialogDescription>{practice.bookingUrl||practice.phone?<div className="booking-links">{practice.bookingUrl&&<><a className="btn" href={practice.bookingUrl} target="_blank" rel="noopener noreferrer">{t.bookingOnline}<ArrowRight/></a><p className="small-note">{t.bookingExternal}</p></>}{practice.phone&&<a className="btn secondary" href={`tel:${practice.phone.replace(/[^+0-9]/g,'')}`}><Phone/>{practice.phone}</a>}</div>:<div className="info-box"><strong>{t.concept}</strong><p>{t.bookingDemo}</p></div>}<a href={pathFor(lang,'contact')} className="text-link">{t.bookingContact}<ArrowRight/></a></DialogContent></Dialog>;
}
export function LanguageSwitch({lang,alternate}:{lang:Lang;alternate:string}){return <div className="language" aria-label={lang==='de'?'Sprache wählen':'Choose language'}><a href={lang==='de'?'#':alternate} lang="de" hrefLang="de" aria-current={lang==='de'?'page':undefined} aria-label="Deutsch">DE</a><span aria-hidden="true">/</span><a href={lang==='en'?'#':alternate} lang="en" hrefLang="en" aria-current={lang==='en'?'page':undefined} aria-label="English">EN</a></div>}
export function MobileMenu({lang,alternate}:{lang:Lang;alternate:string}){const t=ui[lang];const pages:PageKey[]=['services','team','patients','contact'];return <Sheet><SheetTrigger asChild><button className="mobile-toggle" aria-label={t.menu}><Menu/></button></SheetTrigger><SheetContent className="mobile-menu" showCloseButton={false}><SheetClose className="dialog-close" aria-label={t.close}><X/></SheetClose><SheetTitle>ALIN</SheetTitle><SheetDescription>{t.footerTag}</SheetDescription><nav aria-label={t.menu}>{pages.map((p,i)=><a key={p} href={pathFor(lang,p)}>{t.nav[i]}</a>)}<a href={pathFor(lang,'first')}>{t.firstLabel}</a></nav><LanguageSwitch lang={lang} alternate={alternate}/><BookingButton lang={lang}/></SheetContent></Sheet>}
export function FAQ({lang}:{lang:Lang}){return <Accordion type="single" collapsible className="faq-list">{faq[lang].map(([q,a],i)=><AccordionItem value={`question-${i}`} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion>}
const photos=['reception','treatment','consultation'];
export function Gallery({lang}:{lang:Lang}){const t=ui[lang];const [selected,setSelected]=useState<number|null>(null);return <><div className="gallery-grid">{photos.map((photo,i)=><button className="gallery-item" key={photo} onClick={()=>setSelected(i)} aria-label={`${t.galleryNames[i]} – ${lang==='de'?'Bild vergrößern':'enlarge image'}`}><img src={`/images/${photo}-800.webp`} srcSet={`/images/${photo}-800.webp 800w, /images/${photo}-1400.webp 1400w`} sizes="(max-width:680px) 90vw, 33vw" width={800} height={533} alt={`${t.galleryNames[i]}. ${t.imageNote}.`} loading="lazy"/><span className="gallery-caption">{t.galleryNames[i]}<Expand aria-hidden="true"/></span></button>)}</div><p className="small-note">{t.photoCredit}</p><Dialog open={selected!==null} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="lightbox-dialog" showCloseButton={false} onKeyDown={e=>{if(e.key==='ArrowRight')setSelected(v=>v===null?0:(v+1)%photos.length);if(e.key==='ArrowLeft')setSelected(v=>v===null?0:(v+photos.length-1)%photos.length)}}><DialogClose className="dialog-close" aria-label={t.close}><X/></DialogClose><img src={`/images/${photos[selected??0]}-1400.webp`} width={1400} height={933} alt={`${t.galleryNames[selected??0]}. ${t.imageNote}.`}/><div className="lightbox-bottom"><div><DialogTitle>{t.galleryNames[selected??0]}</DialogTitle><DialogDescription className="small-note">{t.imageNote}</DialogDescription></div><div className="lightbox-controls"><button className="icon-button" aria-label={lang==='de'?'Vorheriges Bild':'Previous image'} onClick={()=>setSelected(v=>((v??0)+photos.length-1)%photos.length)}><ArrowLeft/></button><button className="icon-button" aria-label={lang==='de'?'Nächstes Bild':'Next image'} onClick={()=>setSelected(v=>((v??0)+1)%photos.length)}><ArrowRight/></button></div></div></DialogContent></Dialog></>}
export function PrintButton({lang}:{lang:Lang}){return <button className="btn secondary" onClick={()=>window.print()}><Printer/>{ui[lang].print}</button>}
