import {ArrowRight,ChevronRight,CalendarDays,MapPin,Phone,Mail,Clock,HeartHandshake,ShieldCheck,Sparkles,Leaf,Smile,Gem,MessageCircle,UserRound,Check,Stethoscope} from 'lucide-react';
import {practice,ui,Lang,PageKey,pathFor} from '@/lib/practice';
import {treatments,treatmentPath} from '@/lib/treatments';
import {BookingButton,LanguageSwitch,MobileMenu} from './interactive';
import type {ReactNode} from 'react';
export function Lines({text}:{text:string}){return <>{text.split('\n').map((line,i)=><span key={line}>{i>0&&<br/>}{line}</span>)}</>}
export function TextLink({href,children}:{href:string;children:ReactNode}){return <a href={href} className="text-link">{children}<ArrowRight aria-hidden="true"/></a>}
export function Brand({lang}:{lang:Lang}){return <a className="brand" href={pathFor(lang)} aria-label="ALIN – Home"><img className="brand-symbol" src="/images/alin-logo.png" width={70} height={70} alt=""/><span><span className="brand-name">ALIN</span><span className="brand-sub">{lang==='de'?'ZAHNMEDIZIN MIT GEFÜHL':'DENTISTRY WITH A HUMAN TOUCH'}</span></span></a>}
export function Header({lang,page,alternate}:{lang:Lang;page:PageKey;alternate:string}){const t=ui[lang];const nav:PageKey[]=['services','team','patients','contact'];return <><a href="#main" className="skip">{t.skip}</a>{practice.concept&&<div className="concept-bar">{lang==='de'?'ALIN · Ein fiktives Praxiskonzept mit KI-generierten Bildern':'ALIN · A fictional practice concept with AI-generated images'}</div>}<header className="site-header"><div className="wrap header-inner"><Brand lang={lang}/><nav className="desktop-nav" aria-label={t.menu}>{nav.map((p,i)=><a key={p} href={pathFor(lang,p)} aria-current={page===p?'page':undefined}>{t.nav[i]}</a>)}</nav><div className="header-actions"><LanguageSwitch lang={lang} alternate={alternate}/><BookingButton lang={lang}/><MobileMenu lang={lang} alternate={alternate}/></div></div></header>{practice.notice[lang]&&(!practice.notice.expires||Date.parse(practice.notice.expires)>Date.now())&&<aside className="site-notice">{practice.notice[lang]}</aside>}</>}
export function Footer({lang}:{lang:Lang}){const t=ui[lang];return <><footer className="site-footer"><div className="wrap"><div className="footer-grid"><div className="footer-intro"><Brand lang={lang}/><p>{t.footerTag}<br/>{lang==='de'?'Persönlich. Verständlich. Zugewandt.':'Personal. Clear. Considerate.'}</p></div><div className="footer-column"><strong>{t.footerExplore}</strong><a href={pathFor(lang,'services')}>{t.nav[0]}</a><a href={pathFor(lang,'team')}>{t.nav[1]}</a><a href={pathFor(lang,'contact')}>{t.contactLink}</a></div><div className="footer-column"><strong>{t.footerPatients}</strong><a href={pathFor(lang,'first')}>{lang==='de'?'Ihr erster Besuch':'Your first visit'}</a><a href={pathFor(lang,'anxiety')}>{lang==='de'?'Angstpatienten':'Dental anxiety'}</a><a href={pathFor(lang,'costs')}>{lang==='de'?'Kosten & Versicherung':'Costs & insurance'}</a><a href={practice.emergencyUrl} target="_blank" rel="noopener noreferrer">{t.footerEmergency}</a></div><div className="footer-column"><strong>{t.footerLegal}</strong><a href={pathFor(lang,'legal')}>{lang==='de'?'Impressum':'Legal notice'}</a><a href={pathFor(lang,'privacy')}>{lang==='de'?'Datenschutz':'Privacy'}</a></div></div><div className="footer-bottom"><span>© 2026 ALIN · {t.copyright}</span>{practice.concept&&<p>{t.conceptNote}</p>}</div></div></footer><div className="mobile-bar">{practice.phone?<a className="btn secondary" href={`tel:${practice.phone.replace(/[^+0-9]/g,'')}`}><Phone/>{t.call}</a>:<a className="btn secondary" href={pathFor(lang,'contact')}><MessageCircle/>{t.nav[3]}</a>}<BookingButton lang={lang} short/></div></>}
export function Intro({lang,title,description,label,parent}:{lang:Lang;title:string;description:string;label?:string;parent?:{name:string;url:string}}){return <section className="page-intro"><div className="wrap"><nav className="breadcrumb" aria-label={lang==='de'?'Seitenpfad':'Breadcrumb'}><a href={pathFor(lang)}>{ui[lang].home}</a><ChevronRight/>{parent&&<><a href={parent.url}>{parent.name}</a><ChevronRight/></>}<span aria-current="page">{title}</span></nav>{label&&<span className="eyebrow">{label}</span>}<h1>{title}</h1><p>{description}</p></div></section>}
export function SidePanel({lang}:{lang:Lang}){return <aside className="side-panel"><MessageCircle/><h3>{lang==='de'?'Lassen Sie uns sprechen.':'Let’s talk.'}</h3><p>{lang==='de'?'Ihre Fragen verdienen verständliche Antworten. Ein persönliches Gespräch ist der erste Schritt.':'Your questions deserve clear answers. A personal conversation is the first step.'}</p><BookingButton lang={lang}/><TextLink href={pathFor(lang,'costs')}>{lang==='de'?'Kosten & Versicherung':'Costs & insurance'}</TextLink></aside>}
const icons={sparkles:Sparkles,tooth:Stethoscope,leaf:Leaf,gem:Gem,smile:Smile,shield:ShieldCheck};
export function Services({lang}:{lang:Lang}){return <div className="services-grid">{treatments.map((t,i)=>{const Icon=icons[t.icon as keyof typeof icons];return <a className="service-card" key={t.id} href={treatmentPath(lang,t)}><div className="service-top"><span className="service-icon"><Icon aria-hidden="true"/></span><span className="service-num">0{i+1}</span></div><h3>{t[lang].title}</h3><p>{t[lang].short}</p><span className="service-bottom">{ui[lang].more}<ArrowRight aria-hidden="true"/></span></a>})}</div>}
export function ContactFacts({lang}:{lang:Lang}){const t=ui[lang];return <div className="contact-facts"><div className="fact"><span><MapPin/>{t.address}</span><p>{practice.address||t.pending}{practice.city&&<><br/>{practice.postcode} {practice.city}</>}</p></div><div className="fact"><span><Clock/>{t.hours}</span>{practice.hours.length?practice.hours.map(h=><p key={h.day}>{h.day}: {h.time}</p>):<p>{t.pending}</p>}</div><div className="fact"><span><Phone/>{t.phone}</span><p>{practice.phone?<a href={`tel:${practice.phone.replace(/[^+0-9]/g,'')}`}>{practice.phone}</a>:t.pending}</p></div><div className="fact"><span><Mail/>{t.email}</span><p>{practice.email?<a href={`mailto:${practice.email}`}>{practice.email}</a>:t.pending}</p></div></div>}
export function ContactSection({lang}:{lang:Lang}){const t=ui[lang];return <section className="section"><div className="wrap contact-block"><div><span className="eyebrow">{t.contactLabel}</span><h2><Lines text={t.contactTitle}/></h2><p>{t.contactText}</p><TextLink href={pathFor(lang,'contact')}>{t.contactLink}</TextLink></div><ContactFacts lang={lang}/></div></section>}
export function PatientCards({lang}:{lang:Lang}){const t=ui[lang];return <div className="patient-grid"><article className="patient-card"><UserRound aria-hidden="true"/><span className="eyebrow">{t.firstLabel}</span><h2><Lines text={t.firstTitle}/></h2><p>{t.firstText}</p><TextLink href={pathFor(lang,'first')}>{t.firstLink}</TextLink></article><article className="patient-card dark"><HeartHandshake aria-hidden="true"/><span className="eyebrow">{t.anxietyLabel}</span><h2><Lines text={t.anxietyTitle}/></h2><p>{t.anxietyText}</p><TextLink href={pathFor(lang,'anxiety')}>{t.anxietyLink}</TextLink></article></div>}
export function Values({lang}:{lang:Lang}){const data=lang==='de'?[['Zeit zum Zuhören','Fragen und Wünsche gehören an den Anfang jedes Gesprächs.'],['Klarheit statt Fachsprache','Verständliche Informationen helfen bei einer bewussten Entscheidung.'],['Gemeinsam entscheiden','Möglichkeiten, Grenzen und Kosten gehören auf den Tisch.']]:[['Time to listen','Questions and wishes belong at the beginning of every conversation.'],['Clarity over jargon','Understandable information helps you make an informed decision.'],['Decisions made together','Options, limitations and costs deserve an open discussion.']];const icons=[MessageCircle,Check,HeartHandshake];return <div className="values-row">{data.map(([h,p],i)=>{const Icon=icons[i];return <div key={h}><Icon aria-hidden="true"/><h3>{h}</h3><p>{p}</p></div>})}</div>}
