import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {practice,Lang,PageKey,routeNames,pathFor,ui} from '@/lib/practice';
import {treatments,treatmentPath} from '@/lib/treatments';
import {Header,Footer} from '@/components/site/shared';
import {HomePage,ServicesPage,TreatmentPage,TeamPage,PatientsPage,FirstVisitPage,AnxietyPage,CostsPage,ContactPage,LegalPage,PrivacyPage} from '@/components/site/pages';

type Params={lang:string;slug?:string[]};
export const dynamicParams=false;
export function generateStaticParams(){return (['de','en'] as Lang[]).flatMap(lang=>[...Object.keys(routeNames).map(k=>({lang,slug:routeNames[k as PageKey][lang]?[routeNames[k as PageKey][lang]]:[]})),...treatments.map(t=>({lang,slug:[routeNames.services[lang],t.slug[lang]]}))]);}
function resolve(p:Params){if(p.lang!=='de'&&p.lang!=='en')return null;const lang=p.lang as Lang;const slug=(p.slug||[]).join('/');const treatment=treatments.find(t=>slug===`${routeNames.services[lang]}/${t.slug[lang]}`);if(treatment)return {lang,page:'services' as PageKey,treatment};const page=(Object.keys(routeNames) as PageKey[]).find(k=>routeNames[k][lang]===slug);return page?{lang,page,treatment:null}:null;}
const titles={de:{home:'Zahnmedizin mit Gefühl',services:'Leistungen',team:'Praxis & Team',patients:'Für Patienten',first:'Ihr erster Besuch',anxiety:'Für Angstpatienten',costs:'Kosten & Versicherung',contact:'Kontakt & Anfahrt',legal:'Impressum',privacy:'Datenschutz'},en:{home:'Dentistry with a human touch',services:'Treatments',team:'Practice & team',patients:'For patients',first:'Your first visit',anxiety:'Dental anxiety',costs:'Costs & insurance',contact:'Contact & directions',legal:'Legal notice',privacy:'Privacy'}};
export async function generateMetadata({params}:{params:Promise<Params>}):Promise<Metadata>{const r=resolve(await params);if(!r)return {title:'Seite nicht gefunden · ALIN',robots:{index:false}};const {lang,page,treatment}=r;const other=lang==='de'?'en':'de';const current=treatment?treatmentPath(lang,treatment):pathFor(lang,page);const alt=treatment?treatmentPath(other,treatment):pathFor(other,page);const title=`${treatment?treatment[lang].title:titles[lang][page]} | ALIN`;const description=treatment?treatment[lang].intro:page==='home'?ui[lang].heroText:lang==='de'?`${titles.de[page]} – verständliche Informationen bei ALIN.`:`${titles.en[page]} – clear information from ALIN.`;return {...(practice.siteUrl?{metadataBase:new URL(practice.siteUrl)}:{}),title,description,robots:{index:!practice.concept,follow:!practice.concept},...(practice.siteUrl?{alternates:{canonical:current,languages:{[lang]:current,[other]:alt,'x-default':treatment?treatmentPath('de',treatment):pathFor('de',page)}}}:{}),openGraph:{title,description,type:'website',locale:lang==='de'?'de_DE':'en_GB',...(practice.siteUrl?{url:current}:{})}};}
export default async function Page({params}:{params:Promise<Params>}){const r=resolve(await params);if(!r)notFound();const {lang,page,treatment}=r;const other=lang==='de'?'en':'de';const alternate=treatment?treatmentPath(other,treatment):pathFor(other,page);const PageComponent={home:HomePage,services:ServicesPage,team:TeamPage,patients:PatientsPage,first:FirstVisitPage,anxiety:AnxietyPage,costs:CostsPage,contact:ContactPage,legal:LegalPage,privacy:PrivacyPage}[page];const dentistSchema=!practice.concept&&practice.address&&practice.phone?{'@context':'https://schema.org','@type':'Dentist','@id':`${practice.siteUrl}/#practice`,name:practice.name,url:practice.siteUrl,telephone:practice.phone,address:{'@type':'PostalAddress',streetAddress:practice.address,postalCode:practice.postcode,addressLocality:practice.city,addressCountry:'DE'}}:null;return <><Header lang={lang} page={page} alternate={alternate}/><main id="main" tabIndex={-1}>{treatment?<TreatmentPage lang={lang} treatment={treatment}/>:<PageComponent lang={lang}/>}</main><Footer lang={lang}/>{dentistSchema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(dentistSchema).replace(/</g,'\\u003c')}}/>}</>}
